modLoader = "javafml"
loaderVersion = "[37,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "walkers"
version = "${version}"
displayName = "Walkers"
authors = "To_Craft"
description = '''
Become a Woodwalker/animagus!
'''
#logoFile = ""

[[dependencies.walkers]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.walkers]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.walkers]]
modId = "architectury"
mandatory = true
versionRange = "[2.3.23,)"
ordering = "AFTER"
side = "BOTH"