name: Fabric Build
on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
    runs-on: ubuntu-20.04
    container:
      image: openjdk:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew check build publishToMavenLocal --stacktrace --parallel
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
